### ISSUE TITLE
프론트엔드 개발 환경 설정

### ISSUE THREAD

**Issue by wooojini** [boostcamp-2020/IssueTracker-40#1]
## 💁 설명

협업을 위해 필요한 기초적인 프론트엔드 개발 환경 설정에 대한 이슈이다. 

## 📑 체크리스트

> 구현해야하는 이슈 체크리스트

- [x] 리액트 빌드 환경 구축
  - 리액트 바벨 트랜스파일링 설정
  - 리액트 라우터 설정

- [x] 웹팩 설정
  - 웹팩 환경에 따른 설정
    - development
    - production

- [x] 환경변수 설정
  - dotenv 활용 환경변수 설정
  - 웹팩 설정 코드에서 자동으로 환경변수 추가

- [x] 폴더 구조 설정
  - config
    - 환경변수 참조 모듈
  - env
    - 환경변수를 정의하는 .env파일이 위치하는 폴더
  - public
    - 정적 파일 폴더
    - index.html, imgs....
  - src
    - 번들링 소스 폴더
    - 컴포넌트
    - jsx 파일들
  - src/common
    - hook
      - 커스텀 hook 파일 폴더
    - sytle
      - scss 스타일 폴더
    - utils
      - util 모듈 파일 폴더
    - lib
      - 외부 모듈 폴더
    - client
      - Root 컴포넌트
        - 최상위 App 컴포넌트 렌더링 전에 해주어야 할 작업들
        - ReactRouter, Redux... 
    - shared
      - App.js 
        - 최상위 컴포넌트
        - 클라이언트 라우팅
- [x] ESLint / Prettier 통합 설정
  - ESLint 설정
    - Airbnb 스타일 가이드
  - Prettier 설정
    - 커스텀 Prettier 설정
    - ESLint 통합 설정

- [x] 기본 스타일 설정
  - reset.scss
    - 스타일 초기화 
    - 크로스 브라우징
  - common.scss
    - 재활용 스타일 정의
  - mixin.scss
    - 믹스인 정의 

## 🚧 주의 사항

> 이슈를 구현할 때 유의깊게 살펴볼 사항

- 이슈는 4명 모두가 같이 진행한다.

**Comment by Do-ho** [comment]
webpack 파일을 보던 중 scss를 번들링 해주는 부분이 없는 것 같아요! 현재 head에 css가 들어가는 모습을 볼 수 있습니다. mini-css-extract-plugin를 사용하는 것이 맞겠져...?

**Comment by wooojini** [comment]
@Do-ho 잊고있었는데 플러그인 사용해서 CSS 따로 번들링 해주는게 좋아보입니다 :-) 오늘 설정추가해놓을게요!
