### ISSUE TITLE
마일스톤, 댓글 조회 응답 결과가 보내지지 않은 버그

### ISSUE THREAD

**Issue by Do-ho** [boostcamp-2020/IssueTracker-40#108]
## 💁 설명

마일스톤, 댓글 조회 응답 결과가 보내지지 않은 버그

## 📑 체크리스트

> 구현해야하는 이슈 체크리스트

- [x] 마일스톤 조회에 대한 응답 결과 전송
- [x] 댓글 조회에 대한 응답 결과 전송

## 🚧 주의 사항

> 이슈를 구현할 때 유의깊게 살펴볼 사항

- API 스웨거 문서를 참조해 작성

**Comment by jinhyukoo** [comment]
체크리스트에 똑같은게 2개네용!? ㅋㅋㅋ

**Comment by Do-ho** [comment]
ㅋㅋㅋㅋㅋ 수정했습니다!
