### ISSUE TITLE
사이드바 컴포넌트 구현

### ISSUE THREAD

**Issue by Do-ho** [boostcamp-2020/IssueTracker-40#11]
## 💁 설명

공통 컴포넌트인 재사용 가능한 사이드바를 구현한다.
<img width="325" alt="스크린샷 2020-10-29 오후 3 21 27" src="https://user-images.githubusercontent.com/33643752/97532796-6ad82280-19fa-11eb-9ad1-d09bf89d5627.png">

## 📑 체크리스트

> 구현해야하는 이슈 체크리스트

- [ ] 프로젝트에 공통으로 사용할 수 있도록 구현
- [ ] 네이밍은 다음과 같이 한다. CommonSideBar

## 🚧 주의 사항

> 이슈를 구현할 때 유의깊게 살펴볼 사항

- 재사용 가능하도록 구현해주세요.

**Comment by jinhyukoo** [comment]
사이드바 메뉴를 제작해보니 굳이 컴포넌트화 시킬 필요가 없다고 느껴져 이슈를 close 하겠습니다!
