### ISSUE TITLE
백엔드 환경변수 버그 제보

### ISSUE THREAD

**Issue by jinhyukoo** [boostcamp-2020/IssueTracker-40#20]
## 💁 설명

process.env.PWD가 윈도우에서는 undefined로 인식되는 문제가 있네요.
고쳐주시면 감사드립니다!

## 📑 체크리스트

> 구현해야하는 이슈 체크리스트

- [x] process.env.PWD 윈도우에서도 인식할 수 있게 수정부탁드립니다.

## 🚧 주의 사항

> 이슈를 구현할 때 유의깊게 살펴볼 사항

- 윈도우에서의 결과를 건홍님께서 테스트 하실 수 없으니 슬랙에 알려주시면 다른 사람이 테스트 해보는 쪽으로 하면 좋겠네요!

**Comment by Do-ho** [comment]
슬랙에 남겨주시면 테스트 돕겠습니다!
