### ISSUE TITLE
이슈 생성/조회 API 구현

### ISSUE THREAD

**Issue by wooojini** [boostcamp-2020/IssueTracker-40#36]
## 💁 설명

이슈를 생성/조회하는 API를 구현한다.

## 📑 체크리스트

> 구현해야하는 이슈 체크리스트

- [ ] 이슈 생성 API 구현
- [ ] 이슈 조회 API 구현
- [ ] 세부 이슈 조회 API 구현

## 🚧 주의 사항

> 이슈를 구현할 때 유의깊게 살펴볼 사항

- [swagger 참조](https://app.swaggerhub.com/apis-docs/issueTrack/issueTracker/1.0.0#/)
- q=is:open author:youngxpepp label:bug label:feature 
모두 and 연산을 통해 검색한다.
- author, milestone, assignee는 다중 선택 불가능
- id로 할 것인가? name으로 할 것인가?

**Comment by youngxpepp** [comment]
이슈 두 개로 분리
#85 #86
