### ISSUE TITLE
⚠️ 연관 관계 수정 필요!

### ISSUE THREAD

**Issue by youngxpepp** [boostcamp-2020/IssueTracker-40#64]
## 💁 설명

아래 언급된 부분에서 연관 관계 설정이 잘못 되어 있는 것을 확인함. (참고자료: https://typeorm.io/#/many-to-one-one-to-many-relations)

https://github.com/boostcamp-2020/IssueTracker-40/blob/54dc612d1ef84f40e7c248cb8f5491df804c3d3b/backend/src/model/comment.js#L25-L29

https://github.com/boostcamp-2020/IssueTracker-40/blob/54dc612d1ef84f40e7c248cb8f5491df804c3d3b/backend/src/model/issue.js#L38-L39

https://github.com/boostcamp-2020/IssueTracker-40/blob/54dc612d1ef84f40e7c248cb8f5491df804c3d3b/backend/src/model/issue.js#L44-L45

https://github.com/boostcamp-2020/IssueTracker-40/blob/54dc612d1ef84f40e7c248cb8f5491df804c3d3b/backend/src/model/issue.js#L47-L48

https://github.com/boostcamp-2020/IssueTracker-40/blob/54dc612d1ef84f40e7c248cb8f5491df804c3d3b/backend/src/model/issue.js#L50-L51

https://github.com/boostcamp-2020/IssueTracker-40/blob/54dc612d1ef84f40e7c248cb8f5491df804c3d3b/backend/src/model/milestone.js#L39-L40

https://github.com/boostcamp-2020/IssueTracker-40/blob/54dc612d1ef84f40e7c248cb8f5491df804c3d3b/backend/src/model/user.js#L37-L41

## 📑 체크리스트

> 구현해야하는 이슈 체크리스트

- [ ] 연관 관계 수정

## 🚧 주의 사항

> 이슈를 구현할 때 유의깊게 살펴볼 사항

- 공식 문서 충분히 참조 후에 연관 관계 수정할 것

**Comment by jinhyukoo** [comment]
코드를 가져오는 기능은 어떻게 사용하는건가욬ㅋㅋㅋ 신기하네용!

**Comment by youngxpepp** [comment]
> 코드를 가져오는 기능은 어떻게 사용하는건가욬ㅋㅋㅋ 신기하네용!

ㅋㅋㅋㅋㅋ내일 화면공유로 알려드리겠습니다
